{% set name = "polib" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fad87d13696127ffb27ea0882d6182f1a9cf8a5e2b37a587751166c51e5a332a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - polib
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://bitbucket.org/izi/polib/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A library to manipulate gettext files (po and mo files).'
  description: |
    * polib allows you to manipulate, create, modify gettext files (pot, po and
      mo files). You can load existing files, iterate through it's entries,
      add, modify entries, comments or metadata, etc... or create new po files
      from scratch.

    * polib supports out of the box any version of python ranging from 2.4 to
    * latest 3.X version.

    * polib is pretty stable now and is used by many opensource projects.
  dev_url: https://bitbucket.org/izi/polib/wiki/Home
  doc_url: https://polib.readthedocs.io/en/latest/
    
extra:
  recipe-maintainers:
    - stuertz
    - kcemenike
