travis:
  secure:
    BINSTAR_TOKEN: HdBRJw3khAIK+oVbRdVsFktBQVilCwHw8ZqqZjQQnvm2XSkO1eOWj5xe1hWWabCyxYPE7pFQ12Wnm/Rs8jruEarEJmVy4j9e+YUfktshqUaGTkovDdoLPPf3FSK4jBKY4z6xmQbS1n0Evhl6icKH+WESslmjEm/52J5wmWAoEpepdqwLhHJIil+t1TNq2oTqymB+wcoUCCIBifsCfDFm0VD0C4IQkUiwNPn15SHrZtdPdVB0zp8g9pPk7zfFo0xV6fkbybEw98VqSV6ZFjpnT2AEVjR2cp1HqTfZ8Gx1HvROad9IffHLghu7om1CrHnIDv6BkU55gwZdTcA+4hUs6lP36SG0qmlEB5pff08Ii9TmBqjekB8Rt0kEfAsPdOCPfULzztLkQSZGigxMBcKrQ3su4ZA8UXCkc9x6fejylP/pH8NqvXCH0xBv1YRNamo9s2pJ7Bj7J03qcJ6b3pER7uZ6gMRqRJSLv9v5uAEj7Qn/ZiZVs6oUyli2HD2UGYwCqcKOTKzsnZ5kGWDxH7e9qkL9GkWdh9JuiPSqYsTNjmOEVAdjM9YdDincDid6dm4X/0MXg1meNSGYPmjxC8sD/Rv/68GHe5YXXKA/JT8CJVl7S8v1PD0Ie5DFxplW1zyOqCqQMAUd0ma7Z7EtFD9EcvC5fkdxdnZbN/dEnHSd4m8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
