travis:
  secure:
    BINSTAR_TOKEN: YU7Zuh96RxuM7G/jRfWoRpaUwAr3Lkha2FyxJ1Ri60IgL9vrHYIiLclz7SkVLenDZGS7/Ih/Ch78lRcy4fGxfZaczDWYsAE21+aVCCBMoUP1Fxpj4ZFSP+aAkoUFMnvcU6xW0nrA7PwYpWhJT93mblKSqm0wSIGdoATDGra1oUZheSiwtM2f4yX7AJea06UXbkbilz0/Gh1uAcYQZvuKNV023G27hALwHEZmUA9rfQNwY4gXLMp9M2h22B3LOqnaS4F7kSGP6D7MnpK9U4XUsD3tFTRJTdrpsxA85XMO5/uhz24u5jizRSVrk1SNtSkdBiOuHYqv2clZFwB7nawPQjO/7Td9J2zZBZzuoZqvT5bsx68HOMoX0DK3X0KVgEmla05CDFMF0tlFeQd5Bg2gOpn6SS94+SNJxxKE3P9ptX3JvxlkaMzFGwZaIwIrfy5D18fqf/d2mu1gzHxO9HwcddqQgDWEIAbFrwz8tApPsWxxUmvuJHV5XLQnrHjU+e7p07CQW1PrP+33JCJ8FlCt7idrh4OJTkEM3hZYqUn/z+uVmoladU37VgBAMkHuzV2RHfnvxLNFOLolA1BMowjcjt/xazj/46XzlnQJevbgSlYOcjDLA29O8ErB/FOV9P2lNjD2l8RYwdBPE0FlMM35/wtbh2jCeRD1th3hc/b6bdw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
