travis:
  secure:
    BINSTAR_TOKEN: GzcG/+d2gaMQzngjK+0zMScHBSKK0X3MXaS9vKqnQUeDC2tp7X0NMj2U0a6pbI/qLiE1GazV12uL7KNyNNrJtZpD8QoFX3DsHPk8sd6f9biXyF9lXrqdm3Zf3JLUb8EWzyCtReDP1egoiLdZa266tMcgUeDK0SGGOSFGayuc356CuvQDcOMdNAJ3Niq1+UC7D+yxrRdEv42yJa1ymlvzWy8LC/YA2Sqft0AqNc6D55vJhPKuxzeqCgC8m7H8hpnmtPFQgCSq8fZ+5Jm6Ezls93uL9dxhkVNXCQPpXqXnNHa0QLAI767tExAVj/dQ1GNMr+T3q2k6SPBOnUn/VLifqE/OAnyZbiztHxgVogdYm0SeUO37zwkDIHPjoB6vqM7hgVOZSYjnYmchQcdpeVb3qRu8kmU9HMXb70e4eSgQKDjAsTY9RjSQOOAkNcMNds6+BlYxHWCJYnHl1KURTmCqqWw8UZKEN++8zm8wStg3H4TNGyXufN8XwZvhdl6iJdknnnKiYoctgExFCPbp3F29xMaYX8RD25oqS5pAymcw5W0TJHdeaBnk9zapgjTk7l13S4zAZz8x1KpJEN66dEm8L/wrIKae5nr64oEiPG9PTAT++LbTqPBqUw7rH99ydhDEWwX8GyLklTHjJQ7oOvzPIHy4lML+wosGns9SUg2ZKRc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
